"""GitHub issue creation/upsert for anomalous fuzzer runs."""

from __future__ import annotations

import logging
import re
from typing import Any

from scripts.fuzzer.models import FuzzerRunAnalysis

logger = logging.getLogger(__name__)

_MARKER_PREFIX = "<!-- valkey-ci-agent:fuzzer-issue:"
_OCCURRENCES_RE = re.compile(r"<!-- valkey-ci-agent:occurrences:(\d+) -->")


class FuzzerIssuePublisher:
    """Creates or updates issues on the target repo for anomalous runs.

    Per-run failures are tolerated: the surrounding loop in `main.py` catches
    exceptions per-run, so a transient GitHub error here just means the next
    cron run will retry against the same fingerprint.
    """

    def __init__(self, github_client: Any) -> None:
        self._gh = github_client

    def upsert_issue(self, repo_name: str, analysis: FuzzerRunAnalysis) -> tuple[str, str]:
        repo = self._gh.get_repo(repo_name)
        fp = analysis.incident_fingerprint or "unknown"
        marker = f"{_MARKER_PREFIX}{fp} -->"
        title = _build_title(analysis)

        existing = self._find_existing(repo_name, marker)

        if existing is None:
            body = _render_body(analysis, marker, occurrences=1)
            issue = repo.create_issue(title=title, body=body)
            if analysis.suggested_labels:
                try:
                    issue.add_to_labels(*analysis.suggested_labels)
                except Exception as exc:
                    logger.info("Could not add labels to issue #%s: %s", issue.number, exc)
            logger.info("Created issue #%s for run %s", issue.number, analysis.run_id)
            return "created", issue.html_url

        body = existing.body or ""
        if marker not in body:
            body = f"{marker}\n{body}".rstrip()
        m = _OCCURRENCES_RE.search(body)
        count = int(m.group(1)) + 1 if m else 2
        new_body = (
            _OCCURRENCES_RE.sub(f"<!-- valkey-ci-agent:occurrences:{count} -->", body)
            if m else f"{body}\n<!-- valkey-ci-agent:occurrences:{count} -->"
        )
        existing.edit(body=new_body, title=title)
        existing.create_comment(body=_render_comment(analysis, count))
        logger.info("Updated issue #%s (occurrence %d)", existing.number, count)
        return "updated", existing.html_url

    def _find_existing(self, repo_name: str, marker: str) -> Any:
        """Find an open issue containing the dedup marker, or None.

        Search failures are propagated so the caller does not silently treat
        them as "no existing issue" (which would cause duplicate issue
        creation). The next cron run will retry against the same fingerprint.
        """
        query = f'"{marker}" in:body repo:{repo_name} is:issue is:open'
        for issue in self._gh.search_issues(query):
            if marker in (issue.body or ""):
                # Reload via the actual repo so we get a mutable issue handle.
                return self._gh.get_repo(repo_name).get_issue(issue.number)
        return None


def _build_title(analysis: FuzzerRunAnalysis) -> str:
    if analysis.root_cause_category:
        label = analysis.root_cause_category.replace("-", " ").replace("_", " ").title()
        return f"[fuzzer-run] {label}"
    if analysis.anomalies:
        return f"[fuzzer-run] {analysis.anomalies[0].title}"
    return "[fuzzer-run] Anomalous behavior detected"


def _render_body(analysis: FuzzerRunAnalysis, marker: str, *, occurrences: int) -> str:
    lines = [
        marker,
        f"<!-- valkey-ci-agent:occurrences:{occurrences} -->",
        "",
        "## Fuzzer Run Analysis",
        "",
        f"**Verdict**: {analysis.triage_verdict}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Run | [{analysis.run_id}]({analysis.run_url}) |",
        f"| Status | `{analysis.overall_status}` |",
        f"| Conclusion | `{analysis.conclusion}` |",
        f"| Scenario | `{analysis.scenario_id or 'unknown'}` |",
        f"| Seed | `{analysis.seed or 'unknown'}` |",
    ]
    if analysis.tested_valkey_sha:
        lines.append(f"| Valkey SHA | `{analysis.tested_valkey_sha}` |")
    lines.extend(["", "### Summary", "", analysis.summary])
    if analysis.anomalies:
        lines.extend(["", "### Findings", ""])
        for a in analysis.anomalies[:10]:
            lines.append(f"- **[{a.severity}]** {a.title}: {a.evidence}")
    if analysis.reproduction_hint:
        lines.extend(["", f"**Reproduce**: `{analysis.reproduction_hint}`"])
    lines.extend(["", "---", "*Generated by valkey-ci-agent*"])
    return "\n".join(lines)


def _render_comment(analysis: FuzzerRunAnalysis, count: int) -> str:
    lines = [
        f"## Occurrence #{count}",
        "",
        f"Run [{analysis.run_id}]({analysis.run_url}) | "
        f"`{analysis.overall_status}` | `{analysis.triage_verdict}`",
        "",
        analysis.summary,
    ]
    if analysis.anomalies:
        lines.append("")
        for a in analysis.anomalies[:5]:
            lines.append(f"- **[{a.severity}]** {a.title}: {a.evidence}")
    return "\n".join(lines)
