"""Render fuzzer analysis results into GitHub issue title, body, and comment text.

The rendering is fuzzer-specific (mentions scenario/seed/Valkey SHA, lists
deterministic anomalies); the surrounding create-or-update machinery lives
in :mod:`scripts.common.issue_dedup`.
"""

from __future__ import annotations

from typing import Callable

from scripts.common.issue_dedup import IssueContent
from scripts.fuzzer.models import FuzzerRunAnalysis

MARKER_NAMESPACE = "valkey-ci-agent:fuzzer-issue"


def render_for(analysis: FuzzerRunAnalysis) -> Callable[[str, int], IssueContent]:
    """Return the render callable expected by ``IssueDedupPublisher.upsert``."""
    def _render(marker: str, occurrences: int) -> IssueContent:
        return IssueContent(
            title=_build_title(analysis),
            body=_render_body(analysis, marker, occurrences=occurrences),
            comment=_render_comment(analysis, occurrences),
            labels=tuple(analysis.suggested_labels),
        )
    return _render


def _build_title(analysis: FuzzerRunAnalysis) -> str:
    if analysis.root_cause_category:
        label = analysis.root_cause_category.replace("-", " ").replace("_", " ").title()
        return f"[fuzzer-run] {label}"
    if analysis.anomalies:
        return f"[fuzzer-run] {analysis.anomalies[0].title}"
    return "[fuzzer-run] Anomalous behavior detected"


def _render_body(analysis: FuzzerRunAnalysis, marker: str, *, occurrences: int) -> str:
    lines = [
        marker,
        f"<!-- {MARKER_NAMESPACE}:occurrences:{occurrences} -->",
        "",
        "## Fuzzer Run Analysis",
        "",
        f"**Verdict**: {analysis.triage_verdict}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Run | [{analysis.run_id}]({analysis.run_url}) |",
        f"| Status | `{analysis.overall_status}` |",
        f"| Conclusion | `{analysis.conclusion}` |",
        f"| Scenario | `{analysis.scenario_id or 'unknown'}` |",
        f"| Seed | `{analysis.seed or 'unknown'}` |",
    ]
    if analysis.tested_valkey_sha:
        lines.append(f"| Valkey SHA | `{analysis.tested_valkey_sha}` |")
    lines.extend(["", "### Summary", "", analysis.summary])
    if analysis.anomalies:
        lines.extend(["", "### Findings", ""])
        for a in analysis.anomalies[:10]:
            lines.append(f"- **[{a.severity}]** {a.title}: {a.evidence}")
    if analysis.reproduction_hint:
        lines.extend(["", f"**Reproduce**: `{analysis.reproduction_hint}`"])
    lines.extend(["", "---", "*Generated by valkey-ci-agent*"])
    return "\n".join(lines)


def _render_comment(analysis: FuzzerRunAnalysis, count: int) -> str:
    lines = [
        f"## Occurrence #{count}",
        "",
        f"Run [{analysis.run_id}]({analysis.run_url}) | "
        f"`{analysis.overall_status}` | `{analysis.triage_verdict}`",
        "",
        analysis.summary,
    ]
    if analysis.anomalies:
        lines.append("")
        for a in analysis.anomalies[:5]:
            lines.append(f"- **[{a.severity}]** {a.title}: {a.evidence}")
    return "\n".join(lines)
