"""Markdown reporting for scheduled backport sweeps."""

from __future__ import annotations

import re

from scripts.backport.sweep_models import (
    DETAIL_ALREADY_ON_SWEEP_BRANCH,
    BranchSweepResult,
    CandidateResult,
)


def result_is_on_backport_branch(result: CandidateResult) -> bool:
    return result.outcome == "applied" or (
        result.outcome == "skipped-existing"
        and result.detail == DETAIL_ALREADY_ON_SWEEP_BRANCH
    )


def repair_diagnosis_from_detail(detail: str) -> str:
    prefix = "Claude repair diagnosis:\n"
    if not detail.startswith(prefix):
        return ""
    body = detail[len(prefix):]
    return body.split("\n\nValidation output:\n", 1)[0].strip()


def validation_failure_detail(output: str) -> str:
    """Preserve AI diagnosis while keeping routine validation logs compact."""
    diagnosis = repair_diagnosis_from_detail(output)
    if not diagnosis:
        return compact_validation_output(output)
    marker = "\n\nValidation output:\n"
    validation_tail = output.split(marker, 1)[1] if marker in output else ""
    return (
        "Claude repair diagnosis:\n"
        f"{diagnosis[:1500]}\n\n"
        "Validation output:\n"
        f"{compact_validation_output(validation_tail)}"
    )


def compact_validation_output(output: str, *, limit: int = 500) -> str:
    text = output.strip()
    if len(text) <= limit:
        return text
    return text[-limit:]


def build_pr_body(
    result: BranchSweepResult,
    *,
    branch_applied: list[CandidateResult] | None = None,
    previous_body: str | None = None,
) -> str:
    lines = [
        f"# Backport sweep for {result.target_branch}",
        "",
        'Automated cherry-picks from PRs marked "To be backported".',
        "",
    ]

    applied = merge_applied_results(
        [r for r in result.results if result_is_on_backport_branch(r)],
        branch_applied=branch_applied,
        previous_body=previous_body,
    )
    failed = [
        r for r in result.results
        if r.outcome not in {"applied", "skipped-existing"}
    ]

    if applied:
        lines.extend(["## Applied", "", "| Source PR | Title | Detail |", "|---|---|---|"])
        for r in applied:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | {_esc(r.detail)} |",
            )
        lines.append("")

    if failed:
        lines.extend([
            "## Needs attention",
            "",
            "These candidates could not be applied automatically and need a maintainer to follow up.",
            "",
            f"<details><summary>{len(failed)} candidate(s)</summary>",
            "",
            "| Source PR | Title | Outcome | Reason |",
            "|---|---|---|---|",
        ])
        for r in failed:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | "
                f"{r.outcome} | {_esc(r.detail)} |",
            )
        lines.extend(["", "</details>", ""])

    lines.extend(["---", "*Generated by valkey-ci-agent using Claude Code.*"])
    return "\n".join(lines)


def build_summary(results: list[BranchSweepResult]) -> str:
    lines = ["## Backport Sweep", ""]
    for r in results:
        applied = sum(1 for c in r.results if result_is_on_backport_branch(c))
        suffix = f" -- [PR]({r.pr_url})" if r.pr_url else ""
        if r.error:
            suffix += f" -- error: {r.error}"
        lines.append(
            f"- `{r.target_branch}`: {applied}/{r.candidates_found} applied" + suffix
        )
    return "\n".join(lines)


def merge_applied_results(
    current: list[CandidateResult],
    *,
    branch_applied: list[CandidateResult] | None = None,
    previous_body: str | None = None,
) -> list[CandidateResult]:
    previous = parse_previous_applied(previous_body or "")
    previous_by_pr = {r.source_pr_number: r for r in previous}
    current_by_pr = {r.source_pr_number: r for r in current}

    if branch_applied is None:
        base_results = [*previous, *current]
    else:
        base_results = [*branch_applied, *current]

    merged: list[CandidateResult] = []
    seen: set[int] = set()
    for base in base_results:
        if base.source_pr_number in seen:
            continue
        seen.add(base.source_pr_number)
        current_result = current_by_pr.get(base.source_pr_number)
        previous_result = previous_by_pr.get(base.source_pr_number)
        merged.append(
            _merge_applied_result(
                base,
                current_result=current_result,
                previous_result=previous_result,
            )
        )
    return merged


def parse_previous_applied(body: str) -> list[CandidateResult]:
    results: list[CandidateResult] = []
    in_applied = False
    for line in body.splitlines():
        stripped = line.strip()
        if stripped == "## Applied":
            in_applied = True
            continue
        if in_applied and stripped.startswith("## "):
            break
        if not in_applied or not stripped.startswith("|"):
            continue

        cells = _split_markdown_table_row(stripped)
        if len(cells) < 3:
            continue
        source, title, detail = cells[:3]
        if source.lower() == "source pr" or set(source) <= {"-"}:
            continue
        match = re.search(r"#(\d+)", source)
        if not match:
            continue
        results.append(
            CandidateResult(
                source_pr_number=int(match.group(1)),
                source_pr_title=title,
                outcome="applied",
                detail=detail,
            )
        )
    return results


def _merge_applied_result(
    base: CandidateResult,
    *,
    current_result: CandidateResult | None,
    previous_result: CandidateResult | None,
) -> CandidateResult:
    if current_result is not None:
        title = current_result.source_pr_title or base.source_pr_title
        detail = current_result.detail
        if detail == DETAIL_ALREADY_ON_SWEEP_BRANCH and previous_result is not None:
            detail = previous_result.detail
    else:
        title = base.source_pr_title
        detail = base.detail
        if previous_result is not None:
            detail = previous_result.detail
            title = title or previous_result.source_pr_title

    return CandidateResult(
        source_pr_number=base.source_pr_number,
        source_pr_title=title,
        outcome="applied",
        detail=detail,
    )


def _split_markdown_table_row(row: str) -> list[str]:
    text = row.strip()
    if text.startswith("|"):
        text = text[1:]
    if text.endswith("|"):
        text = text[:-1]

    cells: list[str] = []
    current: list[str] = []
    escaped = False
    for char in text:
        if char == "\\" and not escaped:
            escaped = True
            current.append(char)
            continue
        if char == "|" and not escaped:
            cells.append(_unesc("".join(current).strip()))
            current = []
            continue
        current.append(char)
        escaped = False
    cells.append(_unesc("".join(current).strip()))
    return cells


def _unesc(value: str) -> str:
    return value.replace("\\|", "|")


def _esc(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")
