"""Markdown reporting for scheduled backport sweeps."""

from __future__ import annotations

import re

from scripts.backport.sweep_models import (
    DETAIL_ALREADY_ON_SWEEP_BRANCH,
    BranchSweepResult,
    CandidateResult,
)


def result_is_on_backport_branch(result: CandidateResult) -> bool:
    if result.outcome == "applied":
        return True
    if result.outcome != "skipped-existing":
        return False
    return result.detail not in {
        "already applied or empty cherry-pick",
        "resolution was already satisfied on target branch",
    }


def repair_diagnosis_from_detail(detail: str) -> str:
    prefix = "Claude repair diagnosis:\n"
    if not detail.startswith(prefix):
        return ""
    body = detail[len(prefix):]
    return body.split("\n\nValidation output:\n", 1)[0].strip()


def validation_failure_detail(output: str) -> str:
    """Preserve AI diagnosis while keeping routine validation logs compact."""
    diagnosis = repair_diagnosis_from_detail(output)
    if not diagnosis:
        return compact_validation_output(output)
    marker = "\n\nValidation output:\n"
    validation_tail = output.split(marker, 1)[1] if marker in output else ""
    return (
        "Claude repair diagnosis:\n"
        f"{diagnosis[:1500]}\n\n"
        "Validation output:\n"
        f"{compact_validation_output(validation_tail)}"
    )


def compact_validation_output(output: str, *, limit: int = 500) -> str:
    text = output.strip()
    if len(text) <= limit:
        return text
    return text[-limit:]


def build_pr_body(
    result: BranchSweepResult,
) -> str:
    lines = [
        f"# Backport sweep for {result.target_branch}",
        "",
        'Automated cherry-picks from PRs marked "To be backported".',
        "",
    ]

    applied = [r for r in result.results if result_is_on_backport_branch(r)]
    failed = [
        r for r in result.results
        if r.outcome not in {"applied", "skipped-existing"}
    ]

    if applied:
        lines.extend(["## Applied", "", "| Source PR | Title | Detail |", "|---|---|---|"])
        for r in applied:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | {_esc(r.detail)} |",
            )
        lines.append("")

    if failed:
        lines.extend([
            "## Needs attention",
            "",
            "These candidates could not be applied automatically and need a maintainer to follow up.",
            "",
            f"<details><summary>{len(failed)} candidate(s)</summary>",
            "",
            "| Source PR | Title | Outcome | Reason |",
            "|---|---|---|---|",
        ])
        for r in failed:
            lines.append(
                f"| #{r.source_pr_number} | {_esc(r.source_pr_title)} | "
                f"{r.outcome} | {_esc(r.detail)} |",
            )
        lines.extend(["", "</details>", ""])

    lines.extend(["---", "*Generated by valkey-ci-agent using Claude Code.*"])
    return "\n".join(lines)


def preserve_existing_applied_details(
    result: BranchSweepResult,
    existing_body: str | None,
) -> None:
    """Carry forward Applied-row details from the current PR body.

    Branch-log reconstruction can prove that a PR is on the sweep branch, but
    it cannot recover whether the original run had details like "conflicts
    resolved by Claude Code". Preserve those annotations when updating an
    existing sweep PR.
    """
    existing_details = _parse_applied_details(existing_body or "")
    if not existing_details:
        return

    for item in result.results:
        if (
            result_is_on_backport_branch(item)
            and item.detail == DETAIL_ALREADY_ON_SWEEP_BRANCH
            and item.source_pr_number in existing_details
        ):
            existing_detail = existing_details[item.source_pr_number]
            if existing_detail:
                item.detail = existing_detail


def build_summary(results: list[BranchSweepResult]) -> str:
    lines = ["## Backport Sweep", ""]
    for r in results:
        applied = sum(1 for c in r.results if result_is_on_backport_branch(c))
        suffix = f" -- [PR]({r.pr_url})" if r.pr_url else ""
        if r.error:
            suffix += f" -- error: {r.error}"
        lines.append(
            f"- `{r.target_branch}`: {applied}/{r.candidates_found} applied" + suffix
        )
    return "\n".join(lines)


def _esc(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _parse_applied_details(body: str) -> dict[int, str]:
    details: dict[int, str] = {}
    in_applied = False

    for raw_line in body.splitlines():
        line = raw_line.strip()
        if line.startswith("## "):
            in_applied = line == "## Applied"
            continue
        if not in_applied or not line.startswith("|"):
            continue

        cells = _split_table_row(line)
        if len(cells) < 3 or _is_table_separator(cells):
            continue
        match = re.search(r"#(\d+)", cells[0])
        if not match:
            continue
        details[int(match.group(1))] = cells[2].strip()

    return details


def _split_table_row(line: str) -> list[str]:
    cells: list[str] = []
    current: list[str] = []
    escaped = False

    for char in line.strip().strip("|"):
        if escaped:
            current.append(char)
            escaped = False
        elif char == "\\":
            escaped = True
        elif char == "|":
            cells.append("".join(current).strip())
            current = []
        else:
            current.append(char)

    cells.append("".join(current).strip())
    return cells


def _is_table_separator(cells: list[str]) -> bool:
    return all(cell and set(cell) <= {"-", ":", " "} for cell in cells)
